version: "3"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: brgarcias/nginx
    networks:
      - node-network
    ports:
      - "80:80"
    depends_on:
      - nodejs

  nodejs:
    build:
      context: node
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=bruno123
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
